version: '3'
services:
  web:
    environment:
      - CLIENTBUILDPATH=/build/
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    volumes:
      - ~/MONGOdata:/data/db
    ports:
      - "27017:27017"
    image: mongo