version: '3'
services:
  web:
    environment:
      - CLIENTBUILDPATH=/build/
      - MONGOHOST=mongo
      - APIHOST=ec2-3-85-142-144.compute-1.amazonaws.com
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - tunn
  mongo:
    volumes:
      - /MONGOdata:/data/db
    ports:
      - "27017:27017"
    image: mongo
    networks:
      - tunn
networks:
  tunn:
    driver: "bridge"